version: '3.8'

services:
  tokenus-flask:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    env_file: .env
    networks:
      - ${NETWORK_NAME}
    restart: always
    volumes:
      - ${VOLUME_NAME}:/app/faiss_index
    expose:
      - "${FLASK_PORT}"
    cpus: "${CPU_LIMIT}"
    mem_limit: ${MEMORY_LIMIT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ${NETWORK_NAME}:
    external: true

volumes:
  ${VOLUME_NAME}:
